
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title><?php echo($page_title); ?> - <?php echo($site_name); ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Styles -->
    <link href="bs/css/bootstrap.min.css" rel="stylesheet">
    <link href="bs/css/bootstrap-responsive.min.css" rel="stylesheet">
    <link href="bs/css/main.css" rel="stylesheet">

    <!-- Icons !-->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="bs/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="bs/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="bs/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="bs/ico/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="bs/ico/favicon.png">

    <!-- Javascript !-->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="bs/js/bootstrap.min.js"></script>    
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="index.php"><?php echo($site_name); ?></a>
          <div class="nav-collapse collapse">
            <ul class="nav">
                <li <?php if($page == "home"){?> class="active" <?php } ?>><a href="index.php">Home</a></li>
                <li <?php if($page == "about"){?> class="active" <?php } ?>><a href="?page=about">About</a></li>
                <li <?php if($page == "contact"){?> class="active" <?php } ?>><a href="?page=contact">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">