<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title><?php echo($page_title); ?> - <?php echo($site_name); ?></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">
        <link rel="stylesheet" href="bs/css/bootstrap.min.css">
        <link rel="stylesheet" href="bs/css/bootstrap-responsive.min.css"/>    
        <link rel="stylesheet" href="bs/css/main.css"/>        
        <style>
            body {
                padding-top: 60px;
                padding-bottom: 40px;
            }
        </style>
        <script src="bs/js/vendor/modernizr-2.6.1-respond-1.1.0.min.js"></script>
    	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>
</head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="index.php"><?php echo($site_name); ?></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li <?php if($page == "home"){?> class="active" <?php } ?>><a href="index.php">Home</a></li>
                            <li <?php if($page == "about"){?> class="active" <?php } ?>><a href="?page=about">About</a></li>
                            <li <?php if($page == "contact"){?> class="active" <?php } ?>><a href="?page=contact">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="container">
